CREATE DATABASE QuanLyBanVeChuyenBay
GO

USE QuanLyBanVeChuyenBay
GO

SET DATEFORMAT DMY
CREATE TABLE HangHangKhong
(
	MAHHK INT IDENTITY PRIMARY KEY,
	TENHHK NVARCHAR(100) NOT NULL
)
GO

CREATE TABLE SanBay
(
	MASANBAY INT IDENTITY PRIMARY KEY,
	TENSANBAY NVARCHAR(100) NOT NULL
)
GO

CREATE TABLE MayBay
(
	MAMAYBAY INT IDENTITY PRIMARY KEY,
	TENMAYBAY NVARCHAR(100) NOT NULL,
	MAHHK INT NOT NULL,
	SOLUONGGHEH1 INT NOT NULL,
	SOLUONGGHEH2 INT NOT NULL

	FOREIGN KEY(MAHHK) REFERENCES dbo.HangHangKhong(MAHHK)
)
GO

CREATE TABLE TuyenBay
(
	MATUYENBAY INT IDENTITY PRIMARY KEY,
	MASANBAYDI INT NOT NULL,
	MASANBAYDEN INT NOT NULL,
	MASANBAYTG INT,
	THOIGIANNGHI TIME,
	THOIGIANBAY TIME NOT NULL
)
GO

CREATE TABLE ChuyenBay
(
	MACHUYENBAY INT IDENTITY PRIMARY KEY,
	MATUYENBAY INT NOT NULL,
	MAMAYBAY INT NOT NULL,
	THOIGIANKHOIHANH DATETIME NOT NULL,
	THOIGIANKETTHUC DATETIME NOT NULL

	--FOREIGN KEY(MATUYENBAY) REFERENCES dbo.TuyenBay(MATUYENBAY),
	--FOREIGN KEY(MAMAYBAY) REFERENCES dbo.MayBay(MAMAYBAY)
)
GO

CREATE TABLE VeChuyenBay
(
	MAVE INT IDENTITY PRIMARY KEY,
	MACHUYENBAY INT NOT NULL,
	LOAIGHE INT NOT NULL,
	GIATIEN INT NOT NULL,
	TINHTRANGVE INT, -- 0: Đã có người đặt. 1: Chưa có người đặt
	NGAYHUY DATE

	--FOREIGN KEY(MACHUYENBAY) REFERENCES dbo.ChuyenBay(MACHUYENBAY)
)
GO

CREATE TABLE KhachHang
(
	MAKHACHHANG INT IDENTITY PRIMARY KEY,
	TENKHACHHANG NVARCHAR(100) NOT NULL,
	CMND NVARCHAR(20) NOT NULL,
	SDT NVARCHAR(15) NOT NULL
)
GO

CREATE TABLE NhanVien
(
	MANHANVIEN INT IDENTITY PRIMARY KEY,
	TENNHANVIEN NVARCHAR(100) NOT NULL
)
GO

CREATE TABLE GiaoDich
(
	MAGIAODICH INT IDENTITY PRIMARY KEY,
	MAVE INT NOT NULL,
	MAKHACHHANG INT NOT NULL,
	MANHANVIEN INT NOT NULL,
	NGAYGIOGD DATETIME NOT NULL,
	HINHTHUCGD NVARCHAR(100) NOT NULL,
	TINHTRANGGD NVARCHAR(100) NOT NULL

	--FOREIGN KEY(MAVE) REFERENCES dbo.VeChuyenBay(MAVE),
	--FOREIGN KEY(MAKHACHHANG) REFERENCES dbo.KhachHang(MAKHACHHANG),
	--FOREIGN KEY(MANHANVIEN) REFERENCES dbo.NhanVien(MANHANVIEN)
)
GO


ALTER TABLE dbo.VeChuyenBay ADD CONSTRAINT FK_VCB_CB FOREIGN KEY(MACHUYENBAY) REFERENCES dbo.ChuyenBay(MACHUYENBAY)

--ALTER TABLE dbo.TuyenBay ADD CONSTRAINT FK_SanBayDi FOREIGN KEY(MASANBAYDI) REFERENCES dbo.SanBay(MASANBAY)
--ALTER TABLE dbo.TuyenBay ADD CONSTRAINT FK_SanBayDen FOREIGN KEY(MASANBAYDEN) REFERENCES dbo.SanBay(MASANBAY)
--ALTER TABLE dbo.TuyenBay ADD CONSTRAINT FK_SanBayTrungGian FOREIGN KEY(MASANBAYTG) REFERENCES dbo.SanBay(MASANBAY)
INSERT INTO CHUYENBAY(MATUYENBAY, MAMAYBAY, THOIGIANKHOIHANH, THOIGIANKETTHUC) VALUES('5', '4', '31/01/2009 12:00:00 AM', '09/01/2009 12:00:00 AM')
 